<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen, projection" />
    <script type="text/javascript" src="/js/libs/jquery-1.6.3.min.js"></script>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>

<div id="wrapper">

    <header id="header">
        <strong>parseKP - Kinopoisk Parser</strong>
    </header><!-- #header-->

    <div id="content">
        <?php echo $this->layout()->content?>
    </div><!-- #content-->

    <footer id="footer"></footer><!-- #footer -->

</div><!-- #wrapper -->
</body>
</html>
